from connectors import *
from mappers import *
from data.action import *
from data.snapshot import *
import sys
import time
import os
import argparse

def main(args):
    global actions, DEJAVU_PATH, connector, snapshot, PLANNER_PATH, DOMAIN_FILE, PROBLEM_FILE
    parser = argparse.ArgumentParser(
        description='RvEPlan python implementation',
        formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument('domain_file', # needed to synthesise the failure handling monitor
        help='PDDL domain file (describing the actions preconditions and effects)',
        type=str)
    parser.add_argument('problem_file', # needed to generate the initial snapshot (and maybe in the future the instantiated failure monitor)
        help='PDDL problem file (describing the initial system setup and goals)',
        type=str)
    # parser.add_argument('plan_file', # what is going to be executed on the system
    #     help='Plan file (generated by the planner)',
    #     type=str)
    parser.add_argument('dejavu_path', # needed to compile and execute the failure handling monitor
        help='Path to Dejavu folder (the one containing dejavu.jar)',
        type=str)
    parser.add_argument('planner_path', # needed to (re)plan
        help='Path to the planner of choice including any flags it may use (e.g.: "/.../fast-downward.sif --alias seq-opt-lmcut")',
        type=str)
    args = parser.parse_args() # maybe in the future we will need more arguments, for now it's just one

    # setup instructions
    os.system('rm ./out/*.csv')
    DEJAVU_PATH = args.dejavu_path
    PLANNER_PATH = args.planner_path
    DOMAIN_FILE = args.domain_file
    PROBLEM_FILE = args.problem_file

    # Generation of the plan (given the Domain and Problem PDDL files)
    os.system(PLANNER_PATH + ' ' + args.domain_file + ' ' + args.problem_file)

    # Translation from PDDL to Failure handling monitor (RVPlan paper)
    os.system('python3 translators/translator.py ' + args.domain_file)
    os.system('java -cp ' + DEJAVU_PATH + '/dejavu.jar dejavu.Verify ./out/prop.qtl | grep -v "Elapsed total"')
    os.system('scalac -cp .:' + DEJAVU_PATH + '/dejavu.jar TraceMonitor.scala 2>&1 | grep -v "warning"')

    # Create snapshot
    # createSnapshot(args.problem_file)

    snapshot = Snapshot(args.problem_file)

    # Connector instantiation
    # connector = JsonConnector() # Domain dependent: With another system, we may use another connector
    connector = raw_connector_logistics.RawConnectorLogistics(raw_mapper.RawMapper())
    with open('./sas_plan', 'r') as plan:
        actions = plan.readlines()
        actions = actions[:-1]
    # initial_propositions = connector.get_initial_propositions()
    # here I am setting the initial propositions to the same ones used in the Problem file
    # however, in general, the initial propositions should come from the system
    snapshot.update(connector.get_initial_propositions())
    initial_propositions = set(snapshot.get_props())
    callbackNewProps(initial_propositions)

def callbackNewProps(props):
    # print(props)
    if props:
        # Update the snapshot
        snapshot.update(props)
    monitor_outcome = '0 errors detected!'
    if not actions:
        # os.system('rm *.class')
        print(snapshot)
        return
    action = Action.fromStrToAction(actions.pop(0))
    print(action)
    with open('./out/trace.csv', 'a') as monitor_input:
        if props:
            # update the failure handling monitor
            for prop in props:
                monitor_input.write(str(prop) + '\n')
        monitor_input.write(str(action))
    monitor_outcome = os.popen('scala -J-Xmx32g -cp .:' + DEJAVU_PATH + '/dejavu.jar TraceMonitor ./out/trace.csv 20  2>&1  | grep -v "Resizing" | grep -v "load BDD package" | grep -v "Garbage collection"').read()
    print(monitor_outcome)
    if '0 errors detected!' not in monitor_outcome:
        with open('./out/trace.csv') as monitor_input:
            lines = monitor_input.readlines()
        with open('./out/trace.csv', 'w') as monitor_input:
            monitor_input.writelines(lines[:-1])
        replan() # replan
    else:
        connector.perform(action, callbackNewProps)

def replan():
    global actions
    # Creation of the newly updated problem file (starting from the snapshot)
    with open('./out/updated_problem.pddl', 'w') as updated_problem_file:
        with open(PROBLEM_FILE, 'r') as old_problem_file:
            instructions = old_problem_file.readlines()
            for instruction in instructions:
                if '(:init' in instruction:
                    index = instruction.index('(:init')
                    updated_problem_file.write(instruction[:index])
                    break
                else:
                    updated_problem_file.write(instruction)
            updated_problem_file.write(str(snapshot) + '\n)')
    # Generation of a new plan (given the Domain and the updated Problem PDDL files)
    os.system(PLANNER_PATH + ' ' + DOMAIN_FILE + ' ' + './out/updated_problem.pddl')
    with open('./sas_plan', 'r') as plan:
        actions = plan.readlines()
        actions = actions[:-1]
    callbackNewProps(set())

if __name__ == '__main__':
    main(sys.argv)
