from connectors import *
import sys
import time
import os
import argparse

def main(args):
    global actions, DEJAVU_PATH
    parser = argparse.ArgumentParser(
        description='RvEPlan python implementation',
        formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument('domain_file', # needed to synthesise the failure handling monitor
        help='PDDL domain file (describing the actions preconditions and effects)',
        type=str)
    parser.add_argument('problem_file', # needed to generate the initial snapshot (and maybe in the future the instantiated failure monitor)
        help='PDDL problem file (describing the initial system setup and goals)',
        type=str)
    parser.add_argument('plan_file', # what is going to be executed on the system
        help='Plan file (generated by the planner)',
        type=str)
    parser.add_argument('dejavu_path', # needed to compile and execute the failure handling monitor
        help='Path to Dejavu folder (the one containing dejavu.jar)',
        type=str)
    args = parser.parse_args() # maybe in the future we will need more arguments, for now it's just one

    # setup instructions
    os.system('rm ./out/*.csv')
    DEJAVU_PATH = args.dejavu_path

    # Translation from PDDL to Failure handling monitor (RVPlan paper)
    os.system('python3 translators/translator.py ' + args.domain_file)
    os.system('java -cp ' + DEJAVU_PATH + '/dejavu.jar dejavu.Verify ./out/prop.qtl | grep -v "Elapsed total"')
    os.system('scalac -cp .:' + DEJAVU_PATH + '/dejavu.jar TraceMonitor.scala 2>&1 | grep -v "warning"')

    # Create snapshot
    createSnapshot(args.problem_file)

    # Connector instantiation
    connector = JsonConnector() # Domain dependent: With another system, we may use another connector
    with open(args.plan_file, 'r') as plan:
        actions = plan.readlines()
    callbackNewProps([])

def callbackNewProps(props):
    monitor_outcome = '0 errors detected!'
    if not actions:
        return
    action = actions.pop(0)
    with open('./out/trace.csv', 'a') as monitor_input:
        if props:
            # Update the snapshot
            updateSnapshot(props)
            # update the failure handling monitor
            for prop in props:
                monitor_input.write(prop + '\n')
        monitor_input.write(action)
    monitor_outcome = os.popen('scala -J-Xmx32g -cp .:' + DEJAVU_PATH + '/dejavu.jar TraceMonitor ./out/trace.csv 20  2>&1  | grep -v "Resizing" | grep -v "load BDD package" | grep -v "Garbage collection"').read()
    if '0 errors detected!' not in monitor_outcome:
        pass # replan
    else:
        connector.perform(action, callbackNewProps)

def createSnapshot(problem):
    pass

def updateSnapshot(props):
    pass

if __name__ == '__main__':
    main(sys.argv)
