(define (problem p01)
 (:domain remote-inspection)
 (:objects cell0 cell1 cell2
           cell3 cell4 cell5
           cell6 cell7 cell8
           cell9 cell10 cell11 - cell
           tank1 tank2 - tank
           rover - robot
)
 (:init
   (robot_at rover cell0)
   (tank_at tank1 cell2)
   (tank_at tank2 cell8)
   (empty cell1)
   (not (empty cell2))
   (empty cell3)
   (empty cell4)
   (empty cell5)
   (empty cell6)
   (empty cell7)
   (not (empty cell8))
   (empty cell9)
   (empty cell10)
   (empty cell11)
   (up cell3 cell0)
   (up cell6 cell3)
   (up cell4 cell1)
   (up cell7 cell4)
   (up cell5 cell2)
   (up cell8 cell5)
   (up cell9 cell6)
   (up cell10 cell7)
   (up cell11 cell8)
   (down cell0 cell3)
   (down cell3 cell6)
   (down cell1 cell4)
   (down cell4 cell7)
   (down cell2 cell5)
   (down cell5 cell8)
   (down cell6 cell9)
   (down cell7 cell10)
   (down cell8 cell11)
   (right cell0 cell1)
   (right cell1 cell2)
   (right cell3 cell4)
   (right cell4 cell5)
   (right cell6 cell7)
   (right cell7 cell8)
   (right cell9 cell10)
   (right cell10 cell11)
   (up cell11 cell8)
   (left cell1 cell0)
   (left cell2 cell1)
   (left cell4 cell3)
   (left cell5 cell4)
   (left cell7 cell6)
   (left cell8 cell7)
   (left cell10 cell9)
   (left cell11 cell10)
   (radiation cell5)
   (not (inspected tank1))
   (not (inspected tank2))
)
 (:goal (and
    (inspected tank1)
    (inspected tank2)
))
)
